### ISSUE TITLE
Create first release

### ISSUE THREAD

**Issue by k00ni** [sweetyrdf/easyrdf#2]
This issue collects all tasks required for the first release of this fork. I first want to make sure, it includes all the previous work (e.g. pull requests) from the original package, was adapted to be more maintainable and is setup properly.

**TODOs:**
* [x] setup Travis
* [x] setup coveralls (for test coverage)
* [x] fix tests
* [x] allow PHP 7.4 tests
* [x] reworked tooling for easier usage and maintenance
* [x] added small docker container to make local development easier
* [x] add `.editorconfig` (https://editorconfig.org/) - it helps developers to apply to our coding styles

It would be cool, if this package could be suggested as the official successor of `easyrdf/easyrdf`, so people using composer see it and can migrate. Maybe njh can set this up. - ref: https://github.com/njh/easyrdf/issues/320 -- **canceled**, no reaction so far

**Releases so far (also available via composer):**
* First alpha: https://github.com/sweetyrdf/easyrdf/releases/tag/1.0-alpha1 :tada:
* Second alpha: https://github.com/sweetyrdf/easyrdf/releases/tag/1.0.0-alpha2
* First release candidate: https://github.com/sweetyrdf/easyrdf/releases/tag/1.0.0-RC1
* **Final release**: https://github.com/sweetyrdf/easyrdf/releases/tag/1.0.0

Outside tests are much appreciated.

**Comment by k00ni** [comment]
1.0.0 got released which is based on the latest master-branch version of EasyRdf, but contains further improvements and some fixes.
