### ISSUE TITLE
About moving code back to easyrdf/easyrdf

### ISSUE THREAD

**Issue by k00ni** [sweetyrdf/easyrdf#20]
* [ ] removed `scripts` folder
* [ ] adapted versions in composer, added dependencies
* [ ] adaptions in `Makefile`
* [ ] refined `.travis.yml`
* [ ] added `DEVELOPER.md`
* [ ] added `phpunit.xml`
* [ ] added `docker` folder

* [ ] #5 - Implement LIBXML_PARSEHUGE to improve XML file parsing
* [ ] #6 - Exact path matching for Resource::get
* [ ] #10 - Sparql\Client uses invalid parameters for `Zend\Http\Client::setHeaders`
* [ ] #13 - Increase timeout to avoid failing tests because no connection possible in time
* [ ] #19 - added support for PHPStan, moved tests to separate namespace, adapted tooling

by @zozlak:
* [ ] #11 - ntriples and turtle parser and serialised fixes
* [ ] #16 - fixes "XML parser converts plus signs into spaces"
* [ ] #18 - fixes "Graph::properties() and Resource::properties() methods handle properties in unknown namespaces properly."

Ref: https://github.com/easyrdf/easyrdf/issues/320
